
RAW:=False

TEST='all'

all:
	python main.py all -f=input.txt --raw=${RAW}

a:
	python main.py a -f=input.txt --raw=${RAW}

b:
	python main.py a -f=input.txt --raw=${RAW}

test-a:
	python main.py a -f=test.txt --raw=${RAW}

test-b:
	python main.py b -f=test.txt --raw=${RAW}
