
RAW:=False

TEST='all'

all:
	python main.py all -f=input.txt

a:
	python main.py a -f=input.txt

b:
	python main.py b -f=input.txt

test-a:
	python main.py a -f=test.txt

test-b:
	python main.py b -f=test.txt
