
RAW:=--raw=True

TEST='all'

all:
	python main.py all -f=input.txt

a:
	python main.py a -f=input.txt ${RAW}

b:
	python main.py b -f=input.txt ${RAW}

test-a:
	python main.py a -f=test.txt ${RAW}

test-b:
	python main.py b -f=test.txt ${RAW}

